networkx==2.5.1
qiskit==0.31.0
qiskit-aer==0.9.1
qiskit-aqua==0.9.5
qiskit-ibmq-provider==0.17.0
qiskit-ignis==0.6.0
qiskit-terra==0.18.3
projectq==0.6.1.post0
cirq==0.13.0
cirq-aqt==0.13.0
cirq-core==0.13.0
cirq-google==0.13.0
cirq-ionq==0.13.0
cirq-pasqal==0.13.0
cirq-rigetti==0.13.0
cirq-web==0.13.0
quimb==1.3.0
qulacs==0.3.0